# Generated by Django 4.1.2 on 2022-10-25 18:43

import builtins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250, null=True)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('dob', models.DateField(verbose_name=builtins.max)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('address', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employee-avatars/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
