# Generated by Django 4.1.2 on 2022-10-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='objectif',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
