# Generated by Django 4.1.2 on 2022-10-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cv', '0002_remove_profile_objectif_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='qualite',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
    ]
